{% set name = "aws-c-io" %}
{% set version = "0.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8e2abf56e20f87383c44af6818235a12f54051b40c98870f44b2d5d05be08641

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-io", max_pin="x.x.x") }}

requirements:
  build:
    - cmake >=3.9
    - {{ compiler('c') }}
    - ninja-base
  host:
    - aws-c-common 0.12.3
    - aws-c-cal 0.9.2
    - s2n {{ s2n }}  # [linux]

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-io${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/io/io.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\io\\io.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-io.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: This is a module for the AWS SDK for C. It handles all IO and TLS work for application protocols.
  description: |
    This is an event driven framework for implementing application protocols. It is built on top of cross-platform
    abstractions that allow you as a developer to think only about the state machine and API for your protocols.
    A typical use-case would be to write something like Http on top of asynchronous-io with TLS already baked in.
    All of the platform and security concerns are already handled for you.
  dev_url: https://github.com/awslabs/aws-c-io
  doc_url: https://github.com/awslabs/aws-c-io


extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
